-- QUESTION 6 --

-- WHICH 5 PRODUCTS HAVE THE HIGHEST PERCENTAGE OF PURCHASES WITH DISCOUNTS APPLIED? -- 
-- THIS SIMPLY MEANS WHICH PRODUCT DEPEND HEAVILY ON DISCOUNT TO SELL?
SELECT * FROM CUSTOMER LIMIT 5;

SELECT ITEM_PURCHASED,
ROUND(SUM(CASE WHEN DISCOUNT_APPLIED = 'YES' THEN 1 ELSE 0 END) / COUNT(*) * 100, 2) AS DISCOUNT_RATE
FROM CUSTOMER
GROUP BY ITEM_PURCHASED
ORDER BY DISCOUNT_RATE DESC
LIMIT 5;

-- OR THIS WAY --
SELECT ITEM_PURCHASED,
ROUND(100 * SUM(CASE WHEN DISCOUNT_APPLIED = 'YES' THEN 1 ELSE 0 END) / COUNT(*), 2) AS DISCOUNT_RATE
FROM CUSTOMER
GROUP BY ITEM_PURCHASED
ORDER BY DISCOUNT_RATE DESC
LIMIT 5;

-- WHICH 10 PRODUCTS HAVE THE HIGHEST PERCENTAGE OF PURCHASES WITHOUT DISCOUNTS APPLIED?
SELECT ITEM_PURCHASED,
ROUND(SUM(CASE WHEN DISCOUNT_APPLIED = 'NO' THEN 1 ELSE 0 END) / COUNT(*) * 100, 2) AS DISCOUNT_RATE
FROM CUSTOMER
GROUP BY ITEM_PURCHASED
ORDER BY DISCOUNT_RATE DESC
LIMIT 10;

