-- QUESTION 2 --

-- WHICH CUSTOMERS USED A DISCOUNT BUT STILL SPENT MORE THAN THE AVERAGE PURCHASE AMOUNT ? --

SELECT CUSTOMER_ID, PURCHASE_AMOUNT
FROM CUSTOMER
WHERE DISCOUNT_APPLIED = "YES" AND PURCHASE_AMOUNT >= (SELECT AVG(PURCHASE_AMOUNT) FROM CUSTOMER);


-- INCLUDE LIMIT --
-- THE LIMIT TO TOP 10

SELECT CUSTOMER_ID, PURCHASE_AMOUNT
FROM CUSTOMER
WHERE DISCOUNT_APPLIED = "YES" AND PURCHASE_AMOUNT >= (SELECT AVG(PURCHASE_AMOUNT) FROM CUSTOMER)
LIMIT 10;
