-- QUESTION 7 --
-- SEGMENT CUSTOMERS INTO NEW, RETURNING, AND LOYAL BASED ON THEIR TOTAL NUMBER OF PREVIOUS PURCHASES, AND SHOW THE COUNT OF EACH SEGMENT. --
-- THIS IS CUSTOMER SEGMENTATION ANALYSIS AND WE USE THE CTE HERE

SELECT * FROM CUSTOMER LIMIT 5;

WITH CUSTOMER_TYPE AS (
SELECT CUSTOMER_ID, PREVIOUS_PURCHASES,
CASE 
	WHEN PREVIOUS_PURCHASES = 1 THEN 'NEW_CUSTOMER'
    WHEN PREVIOUS_PURCHASES BETWEEN 2 AND 10 THEN 'RETURNING_CUSTOMER'
    ELSE 'LOYAL_CUSTOMER'
    END AS CUSTOMER_SEGMENT

FROM CUSTOMER
)

SELECT CUSTOMER_SEGMENT, COUNT(*) AS 'NUMBER_OF_CUSTOMER'
FROM CUSTOMER_TYPE
GROUP BY CUSTOMER_SEGMENT

