-- QUESTION 4 --

-- COMPARE THE AVERAGE PURCHASE AMOUNTS BETWEEN STANDARD AND EXPRESS SHIPPING --
SELECT SHIPPING_TYPE,
AVG(PURCHASE_AMOUNT)
FROM CUSTOMER
WHERE SHIPPING_TYPE IN ("STANDARD", "EXPRESS")
GROUP BY SHIPPING_TYPE;

-- OPTIMISED --
SELECT SHIPPING_TYPE,
ROUND(AVG(PURCHASE_AMOUNT), 2) AS "AVR_PUR_AMT"
FROM CUSTOMER
WHERE SHIPPING_TYPE IN ("STANDARD", "EXPRESS")
GROUP BY SHIPPING_TYPE;


-- COMPARE THE AVERAGE PURCHASE AMOUNTS BETWEEN THE ITEMS IN THE SHIPPING TYPE --
SELECT SHIPPING_TYPE,
ROUND(AVG(PURCHASE_AMOUNT), 2) AS "AVR_PUR_AMT"
FROM CUSTOMER
GROUP BY SHIPPING_TYPE;