-- QUESTION 10 --

-- WHAT IS THE REVENUE CONTRIBUTION OF EACH AGE GROUP? --
-- THIS TELLS US WHICH DEMOGRAPHY IS VALUABLE TO THE BUSINESS AND DRIVE REVENUE--

SELECT * FROM CUSTOMER LIMIT 5;


SELECT AGE_GROUP,
SUM(PURCHASE_AMOUNT) AS TOTAL_REVENUE
FROM CUSTOMER
GROUP BY AGE_GROUP
ORDER BY TOTAL_REVENUE DESC;
