-- QUESTION 3 --

-- WHICH ARE THE TOP 5 PRODUCTS WITH THE HIGHEST AVERAGE REVIEW RATING ? --

SELECT ITEM_PURCHASED, AVG(REVIEW_RATING) AS "AVERAGE_PRODUCT_RATING"
FROM CUSTOMER
GROUP BY ITEM_PURCHASED
ORDER BY AVG(REVIEW_RATING) DESC
LIMIT 5;
