-- QUESTION 2 --

-- WHICH TOP 10 CUSTOMERS USED A DISCOUNT BUT STILL SPENT MORE THAN THE AVERAGE PURCHASE AMOUNT ? --

SELECT CUSTOMER_ID, PURCHASE_AMOUNT
FROM CUSTOMER
WHERE DISCOUNT_APPLIED = "YES" AND PURCHASE_AMOUNT >= (SELECT AVG(PURCHASE_AMOUNT) FROM CUSTOMER)
ORDER BY PURCHASE_AMOUNT DESC
LIMIT 10;


-- INCLUDE LIMIT --
-- THE LIMIT TO TOP 10

SELECT CUSTOMER_ID, PURCHASE_AMOUNT
FROM CUSTOMER
WHERE DISCOUNT_APPLIED = "YES" AND PURCHASE_AMOUNT >= (SELECT AVG(PURCHASE_AMOUNT) FROM CUSTOMER)
ORDER BY PURCHASE_AMOUNT DESC
LIMIT 10;
