-- QUESTION 9 --

-- ARE THOSE CUSTOMERS WHO ARE REPEAT BUYERS (MORE THAN 5 PREVIOUS PURCHASES) ALSO LIKELY TO SUBSCRIBE?

SELECT * FROM CUSTOMER LIMIT 5;

SELECT SUBSCRIPTION_STATUS,
COUNT(CUSTOMER_ID) AS REPEAT_BUYERS
FROM CUSTOMER
WHERE PREVIOUS_PURCHASES > 5
GROUP BY SUBSCRIPTION_STATUS