-- QUESTION 5 --

-- DO SUBSCRIBED CUSTOMERS SPEND MORE? COMPARE AVERAGE SPEND AND TOTAL REVENUE BETWEEN SUBSCRIBERS AND NON-SUBSCRIBERS
SELECT SUBSCRIPTION_STATUS,
COUNT(CUSTOMER_ID) AS TOTAL_CUSTOMER,
ROUND(AVG(PURCHASE_AMOUNT), 2) AS AVERAGE_SPEND,
ROUND(SUM(PURCHASE_AMOUNT), 2) AS TOTAL_REVENUE
FROM CUSTOMER
GROUP BY SUBSCRIPTION_STATUS
ORDER BY TOTAL_REVENUE, AVERAGE_SPEND DESC;


-- OR YOU CAN USE STRINGS FOR THE ALIASES
SELECT SUBSCRIPTION_STATUS,
COUNT(CUSTOMER_ID) AS 'TOTAL_CUSTOMER',
ROUND(AVG(PURCHASE_AMOUNT), 2) AS 'AVERAGE_SPEND',
ROUND(SUM(PURCHASE_AMOUNT), 2) AS 'TOTAL_REVENUE'
FROM CUSTOMER
GROUP BY SUBSCRIPTION_STATUS
ORDER BY TOTAL_REVENUE, AVERAGE_SPEND DESC;
