-- QUESTION 8 --

-- WHAT ARE THE TOP 3 MOST PURCHASED PRODUCTS WITHIN EACH CATEGORY? --
-- HERE WE WOULD USE CTEs AND WINDOW FUNCTION CALLED ROW_NUMBER INSTEAD OF RANK
SELECT * FROM CUSTOMER LIMIT 5;

WITH ITEM_COUNTS AS (
SELECT CATEGORY,
ITEM_PURCHASED,
COUNT(CUSTOMER_ID) AS TOTAL_ORDERS,
ROW_NUMBER() OVER (PARTITION BY CATEGORY ORDER BY COUNT(CUSTOMER_ID) DESC) AS ITEM_RANK
FROM CUSTOMER
GROUP BY CATEGORY, ITEM_PURCHASED
)

SELECT ITEM_RANK, CATEGORY, ITEM_PURCHASED, TOTAL_ORDERS
FROM ITEM_COUNTS
WHERE ITEM_RANK <= 3;
